version: "2"
eslint:
  enabled: true
file-lines:
  config:
    threshold: 50
exclude_patterns:
- "**/node_modules/"
- "**/test/"
- "**/__tests__/"
- "**/tests/"
- "/config/"
- "src/redux/store/__test__/" 
- "scripts/"