version: "2"
eslint:
  enabled: true
checks:
  method-lines:
    config:
      threshold: 35
exclude_patterns:
- "**/node_modules/"
- "**/test/"
- "**/__tests__/"
- "**/tests/"
- "/config/"
- "src/redux/store/__test__/"
- "src/**/__mocks__/"
- "scripts/"